version: "3"

services:
  mysql:
    image: mysql:latest
    #image: yobasystems/alpine-mariadb
    #image: bianjp/mariadb-alpine
    container_name: "${MYSQL_NAME}"
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}    
      #- MYSQL_DATABASE="wordpressdb"
      #- MYSQL_USER=root
      #- MYSQL_PASSWORD=root
    volumes:
    # Montamos un volumen para MySQL para no perder los datos de bd
      - ./volumenes/mysql:/var/lib/mysql
      #- ./volumenes/mysql_logs:/var/lib/mysql/mysql-bin
    expose:
      - 3306
  
  php74:
    build:
      context: .
      dockerfile: docker/74-apache.Dockerfile
    restart: always
    volumes:
      #- ./htdocs/:/var/www/html/
      - ./htdocs/:/var/www/localhost/htdocs/
    container_name: "${PHP_NAME}74"
    expose:
      - 8080
    ports:
      - ${PHP74_PORT}:80
    links: 
      - mysql
  
  php72:
    build:
      context: .
      dockerfile: docker/72-apache.Dockerfile
      args:
        PHP_VERSION: "7.2"
    restart: always
    volumes:
      #- ./htdocs/:/var/www/html/
      - ./htdocs/:/var/www/localhost/htdocs/
    container_name: "${PHP_NAME}72"
    expose:
      - 8080
    ports:
      - ${PHP72_PORT}:80
    links: 
      - mysql
  
  php70:
    build:
      context: .
      dockerfile: docker/70-apache.Dockerfile
      args:
        PHP_VERSION: "7.0"
    restart: always
    volumes:
      #- ./htdocs/:/var/www/html/
      - ./htdocs/:/var/www/localhost/htdocs/
    container_name: "${PHP_NAME}70"
    expose:
      - 8080
    ports:
      - ${PHP70_PORT}:80
    links: 
      - mysql

  phpmyadmin:
    #image: phpmyadmin:fpm-alpine
    #image: phpmyadmin/phpmyadmin:fpm-alpine
    image: phpmyadmin/phpmyadmin
    container_name: "${PHPMYADMIN_NAME}"
    restart: always
    ports: 
      - ${PHPMYADMIN_PORT}:80
    volumes:
      - ./config/phpmyadmin/config.user.inc.php:/etc/phpmyadmin/config.user.inc.php
    environment:
      PMA_HOSTS: mysql
      UPLOAD_LIMIT: 100M
    depends_on:
      - mysql
    links:
      - mysql

  mongo:
    image: mongo
    container_name: ${MONGO_NAME}
    restart: always
    volumes:
      - ./volumenes/mongodb:/data/db
    ports:
      - ${MONGO_PORT}:27017
