ARG PHP_VERSION=""
#FROM php:7.4-fpm-alpine
FROM php:${PHP_VERSION:+${PHP_VERSION}-}fpm-alpine
LABEL maintainer="faviobrntn"

ADD https://github.com/mlocati/docker-php-extension-installer/releases/latest/download/install-php-extensions /usr/local/bin/


RUN chmod +x /usr/local/bin/install-php-extensions && sync && \
    install-php-extensions @composer \
    gd \
    xdebug \
    bcmath \
    bz2 \
    calendar \
    exif \
    intl \
    ldap \
    memcached \
    mysqli \
    opcache \
    pdo_mysql \
    pdo_pgsql \
    pgsql \
    redis \
    soap \
    xsl \
    zip \
    sockets \
    pdo_sqlsrv \
    sqlsrv \
    mongodb

#WORKDIR /usr/local/apache2/htdocs